[project]
name = "libterraform"
version = "0.8.2"
description = "Python binding for Terraform."
authors = [{ name = "Prodesire", email = "wangbinxin001@126.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
keywords = ["libterraform", "terraform"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: BSD",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
Homepage = "https://github.com/Prodesire/py-libterraform"
Repository = "https://github.com/Prodesire/py-libterraform"

[dependency-groups]
dev = ["pytest>=7.0.1", "ruff>=0.5.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["libterraform"]
artifacts = ["libterraform/libterraform.so", "libterraform/libterraform.dll"]

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"
