name: Run Tests

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry pytest
        run: |
          python -m pip install poetry==1.1.13 pytest==7.0.1
      - name: Fetch terraform repository
        run: |
          git submodule init
          git submodule update
      - name: Build distributions
        run: |
          poetry build -f wheel -vvv
      - name: Run tests
        run: |
          pytest
